### ISSUE TITLE
[License] license needed

### ISSUE THREAD

**Issue by Quasimurdock** [Quasimurdock/IELTS-Anki-Cards-Generator#11]
Found `mkanki` takes AGPLv3 as its license: 

> mkanki is licensed to everyone under the terms of the [GNU Affero General Public License v3](https:opensource.org/licenses/AGPL-3.0). If you'd like to use mkanki under different terms, I'm happy to accommodate you—just [email me](mailto:nornagon@nornagon.net)!

I asked GPT and it gave me info as follows:

> If a project you depend on is licensed under the GNU Affero General Public License v3 (AGPLv3), there are specific steps you should take to ensure your GitHub project complies with the terms of this license:
> 
> 1. Clearly Identify Dependencies:
> 
>     - Clearly indicate in your project that you are using components covered by the AGPLv3 license. This can be done through documentation, comments, or other appropriate means.
> 2. Provide Access to Source Code:
> 
>     - If your project provides services over a network and uses AGPLv3-licensed components, ensure that users who interact with your service can access the modified source code. This usually involves providing a way to obtain the source code, such as through a link within your project.
> 3. Include License and Copyright Notices:
> 
>     - Include the full text of the AGPLv3 license and the copyright notices for each AGPLv3-licensed component used in your project. This  is typically done in the root directory or relevant files of your project.
> 4. Update README File:
> 
>     - In your project's README file, explicitly mention that you are using AGPLv3-licensed components and provide a way for users to access the modified source code.
> 5. Comply with AGPLv3 Requirements:
> 
>     - Adhere to the requirements of the AGPLv3 license, which state that even if you do not directly distribute the code, users accessing your project over a network have the right to access and request the modified source code.
> 6. Consider Legal Advice:
> 
>     - As AGPLv3 is a copyleft license with legal implications, it's advisable to consult legal experts to ensure your project fully aligns with the terms of the license.
> 
> Keep in mind that these steps are general guidelines, and the specific actions you need to take might vary based on the nature of your project and legal regulations. When dealing with projects licensed under AGPLv3, it's important to have a comprehensive understanding of the license's requirements and ensure compliance

**Comment by Quasimurdock** [comment]
As far as I know the default license Github takes is MIT license, so we need to modify it.

Considering the tips above, the most confusing to me is the 3rd one. I don't actually know what texts should we add. We need to read official documentation about it.

**Comment by serifold** [comment]
> As far as I know the default license Github takes is MIT license, so we need to modify it.
> 
> Considering the tips above, the most confusing to me is the 3rd one. I don't actually know what texts should we add. We need to read official documentation about it.

I couldn't remember which project put a full text of not only AGPLv3 license, but also other licenses. I think copy and modify a bit from `mkanki`'s [license disclaimer](https://github.com/nornagon/mkanki#license) is enough, just add a link to [GNU Affero General Public License v3](https://opensource.org/licenses/AGPL-3.0).

**Comment by Quasimurdock** [comment]
Licenses added in the [commit](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/commit/b024f25c14f9c5f2af17e2a3f067160ff383784b)
