### ISSUE TITLE
自己获取单词没有发音 怎么办

### ISSUE THREAD

**Issue by bzfzis** [Quasimurdock/IELTS-Anki-Cards-Generator#15]

**Comment by Quasimurdock** [comment]
Hi, can u plz add more discription?

**Comment by bzfzis** [comment]
Add your own words in the "word" file, the exported apkg file has no word pronunciation

**Comment by Quasimurdock** [comment]
> Add your own words in the "word" file, the exported apkg file has no word pronunciation

R u trying to run `pnpm start` or `pnpm start-worker` on the branch `main`? If so, run `git checkout pronun` in your terminal to switch ur git branch to `pronun` cuz for  now pronun feature haven't been merged to main branch

**Comment by bzfzis** [comment]
thanks, i'll try again

**Comment by bzfzis** [comment]
Now the output apkg file has pronunciation, but the words will be lost. The input is about 700 words, and the output is only about 600 words.

**Comment by Quasimurdock** [comment]
> Now the output apkg file has pronunciation, but the words will be lost. The input is about 700 words, and the output is only about 600 words.

For those missing words, u can try to search them on Cambridge Dictionary website to check if they have results or they are redirected to another term pages due to spell differences etc. Some of them may not be collected by the dict, the rest of them are missing due to unknown reasons. I have opened an issue #14 on this before, unsolved yet. Sorry.

**Comment by Quasimurdock** [comment]
Will try to fix this problem this weekend. If u have any further information on it, plz leave them under #14. I'll close this one since the pronun issue is solved.

**Comment by bzfzis** [comment]
> Will try to fix this problem this weekend. If u have any further information on it, plz leave them under #14. I'll close this one since the pronun issue is solved.

It's fine now, thank you very much for your answer
