### ISSUE TITLE
Can't create cards in deck by 'pnpm note'

### ISSUE THREAD

**Issue by serifold** [Quasimurdock/IELTS-Anki-Cards-Generator#2]
Hello,  Quasimurdock. Thanks for your effort and sharing. I want to learn from this project, so I tried to build the project locally. Everything seems normal until the last step:
I run the command `pnpm note`, then the console keeps outputing `Current word: [some word]`..., with no error info;

![image](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/assets/80401151/9539e603-a372-4a55-b0f6-181c6f0e1aa5)

Then I go to Anki, found the IELTS-CamDict-Words deck was auto-generated, but without any cards;

![image](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/assets/80401151/34bcda27-726a-4743-a4f2-c277fd95c06b)

I checked the `html` folder, these files was created normally indeed;

![image](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/assets/80401151/ef0413ee-9879-4289-98df-f6d83e6ba141)

Then I think maybe it's the Anki's new card daily limits that cause the problem, so I adjusted it to 3600, but still can't generate any cards;

![image](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/assets/80401151/9691106b-52e0-41ac-a66a-20f0fa0ec02c)

And I checked the `output/log` foleder, there is only `missing_words.txt`, no `log_html2notes.txt` file, it seems that the `createNewDeck()` runs successfully, cause it created the deck indeed, but the `processHtmlFiles()` can't work normally.

I don't understand why it can't work. Node modules were installed, html files were generated, Anki Connect worked normally, and NO error info can be seen from the console. Could you please share some experience or advice on this problem? Thank you.

My environment info:
OS: Windows 10 22H2
NodeJS version: 18.17.0
Pnpm version: 8.6.11
Anki version:  2.1.65
Anki Connect version: latest

**Comment by serifold** [comment]
Excuse me, I just want to use `Ctrl` + `Enter` to insert new line below the current line, but it auto posted... I updated with some details then.

**Comment by Quasimurdock** [comment]
Hey, @Serifold! Glad to see u give it a try and found a problem.

I think maybe I missed the step which should've added in README. So first u should ①create a new Note Type (Clone from the default [**Basic**] note type. ②Then rename the new note type to **BasicCamCard**. ③Add a new field called [**Word**].

U can try to manually create a new [**Note Type**] (You can find it in the **_Tools - Manage Note Types - Add - Clone:Basic_**）:
![image](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/assets/118411473/b6b0c32c-0795-4166-a378-0d1f9258912d)

![image](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/assets/118411473/1874240c-cc2b-4cb1-927f-eeee90a50724)

The new added field [**Word**] is actually for sorting the words as u can see there's actually no additional field for the word itself if we just clone from the default Basic note type. Otherwise we'll only get a note type with Front and Back fields and it's ugly for browsing ur deck. So remember to check the ratio box [**Sort by this field in the browser**] of field Word in the above image and exclude that of the other two fields.

Finally re-run the command `pnpm note` since u already got those HTML files.

Let me know if it works.

**Comment by Quasimurdock** [comment]
AnkiConnect API for javascript seems actually not returning such kind of error info when it cannot find the specified Note Type (here I say my specified note type is 'BasicCamCard')

**Comment by serifold** [comment]
> AnkiConnect API for javascript seems actually not returning such kind of error info when it cannot find the specified Note Type (here I say my specified note type is 'BasicCamCard')

Thank you very much, @Quasimurdock, 🎉it just works.
But here comes another not serious problem: the amount of cards is less than the amount of html files in the `html` folder, and it seems no error/warn info too.

The File Explorer says I have 3539 items in the `html` folder:

![image](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/assets/80401151/702e0a3d-0ea9-4a25-ab36-042684bf82dc)

and Anki says I have 3535 cards in the deck:

![image](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/assets/80401151/25f5b208-71df-4eae-b0e2-d8050eada123)

Actually, the result 3535 is the second-run result. I get 3536 cards first, then I think, maybe I should re-run it to see if I can get the exactly whole words. Then I re-runned the command, this time I get 3535 cards... And I have tried to search keywords such as 'error'/'warn'/'missing'/'fail' in the terminal, got nothing.
So, the problem now is that I can't get the whole words transformed into cards, and the `pnpm note` process seems unsteady, I tried 2 times, it gave me different amount of cards, and there is no info which words were not included. I know this kind of problem is not serious, but I still want to know if it is possible that I could know which words are missing, or what should I do to get all words into cards?

**Comment by Quasimurdock** [comment]
> and it seems no error/warn info too.

During the running process of `html2notes.js` there should be error logs into `log_html2notes.txt` if any exception is caught. Have u checked that log txt file? If it still misses the key error info maybe I should check out the AnkiConnect API. 

Generating notes into ur anki is also by calling AnkiConnect API as follows:
```javascript
const result = await invoke("addNotes", 6, { notes: notes });
```
Sorry I didn't dig into this deep before. The way to invoke that interface is more like a black box to me. I guess I need to take a detailed look into their API reference to see if any reasonable solutions to this problem.

**Comment by Quasimurdock** [comment]
Btw, it would be better to automatically create that new Note Type behind the scenes. Give me some time on it.

At least I can append the missing steps to README so far, lol.

**Comment by serifold** [comment]
> > and it seems no error/warn info too.
> 
> During the running process of `html2notes.js` there should be error logs into `log_html2notes.txt` if any exception is caught. Have u checked that log txt file? If it still misses the key error info maybe I should check out the AnkiConnect API.
> 
> Generating notes into ur anki is also by calling AnkiConnect API as follows:
> 
> ```js
> const result = await invoke("addNotes", 6, { notes: notes });
> ```
> 
> Sorry I didn't dig into this deep before. The way to invoke that interface is more like a black box to me. I guess I need to take a detailed look into their API reference to see if any reasonable solutions to this problem.

Thanks for your reply, unfortunately, there is still no `log_html2notes.txt`, it seems that `processHtmlFiles()` can't catch errors as we expected.

![image](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/assets/80401151/b2898891-dcd8-4097-b654-5b9bc59443a7)
