### ISSUE TITLE
great program, save me a lot of time.

### ISSUE THREAD

**Issue by finviman** [Quasimurdock/IELTS-Anki-Cards-Generator#5]
some suggestions, when i failed to fetch a word explaination, there are 2 reasons, http 302, means there is no explaination. http 502, means server error. You should split these errors in two different files. Someone should try 502 again, but should not try 302 again.
I know nodejs does not have multi threading features, but it has multi workers, it's great to fetch parallelly.

**Comment by Quasimurdock** [comment]
Thx 4 ur notes, @finviman !

> some suggestions, when i failed to fetch a word explaination, there are 2 reasons, http 302, means there is no explaination. http 502, means server error.

Yes, I'll consider about this status code issue. But I found that there seems to have redirections for some words before. (e.g. Some are American spelling or some are usually used in slangs etc. So the web redirects to another link)  Thus I just set this aside at that time. Well, exception handling is always a trouble lol.

> I know nodejs does not have multi threading features, but it has multi workers, it's great to fetch parallelly.

Sure. I think I'll find some time on it.

**Comment by finviman** [comment]
another wish, fetching pronunciation mp3 and import it to anki.
![0E9D68B8](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/assets/2133400/d47f74b5-9aef-4594-b64e-a0d866862f75)

**Comment by Quasimurdock** [comment]
> another wish, fetching pronunciation mp3 and import it to anki. ![0E9D68B8](https://user-images.githubusercontent.com/2133400/258734081-d47f74b5-9aef-4594-b64e-a0d866862f75.png)

I'll notify u once [this one](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/issues/1) is closed.

**Comment by Quasimurdock** [comment]
@finviman about pronunciation issue I have a thought of making a new Anki plugin for fetching pronunciation online through different available online API interafces that we can find. But I've never written Python and QT, no idea about how hard it is. 

I think that would be better than just fetching pronunciation files for this project. 

It's more general for more users since it can be applied to every different anki card no matter what kind it is. In such case, users may select the text on the card and get pronunciation played by the plugin.

**Comment by Quasimurdock** [comment]
For now u can test these 3 Anki addons:
- [anki-forvo-dl - Forvo Pronunciation Downloader](https://ankiweb.net/shared/info/858591644)
- [AutoDefine](https://ankiweb.net/shared/info/2136497008)
- [Audio and Pronunciation from Merriam - Webster](https://ankiweb.net/shared/info/1878363231)

Addons above seems fine to meet this need.

**Comment by Quasimurdock** [comment]
Hi @finviman 
①`pnpm start-worker` has implemented and ②**pronun supports** will be committed several minutes later.

Now users can play pronun audios of words by clicking on the pronun phonetics
