### ISSUE TITLE
No css style by default. must import by myself

### ISSUE THREAD

**Issue by finviman** [Quasimurdock/IELTS-Anki-Cards-Generator#6]
wierd thing i can not figure out, after i run `pnpm start`, there are many html files and a common.css file. `pnpm note` will import html to anki, but there is no css style. I must copy the common.css content to Note types -> cards -> styling, then they look like  your original deck cards.
Actually I run `pnpm start` in nodejs v16.17, and run `pnpm note` with nodejs v18.13 because there is no buildin fetch function under version 18, Maybe this is the reason?
Any way, amazing product of studing english.

**Comment by Quasimurdock** [comment]
Yeah, now u have to paste the contents of `common.css` to the note type `BasicCamCard` manually. I actually missed the step of creating a new note type automatically. I mentioned this in [#2](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/issues/2#issuecomment-1666818015), sorry.

The problem will be solved later. Note type is actually called Model in AnkiConnect API so I didn't noticed the difference before.

**Comment by Quasimurdock** [comment]
Same as in [#4](https://github.com/Quasimurdock/IELTS-Anki-Cards-Generator/issues/4#issue-1838478916), so I'll close this issue.
